"use client";
import { useEffect, useState, type FormEvent, type ReactNode } from "react";
type Mode = "login" | "signup" | "forgot" | "verify" | "reset";
export default function AuthGate({ children }: { children: ReactNode }) {
  const [user, setUser] = useState<unknown | undefined>();
  const [mode, setMode] = useState<Mode>("login");
  const [email, setEmail] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  useEffect(() => { fetch("/api/auth/email/me").then(r => r.json()).then(d => setUser(d.user)).catch(() => setUser(null)); }, []);
  if (user === undefined) return <div className="min-h-screen grid place-items-center text-sm text-[var(--color-muted)]">Loading secure workspace…</div>;
  if (user) return <>{children}</>;
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); setMessage(""); const data = Object.fromEntries(new FormData(event.currentTarget)); const action = mode === "forgot" ? "send-reset" : mode; const response = await fetch("/api/auth/email", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...data, email: data.email || email, action }) }); const result = await response.json(); if (!response.ok) return setError(result.error || "Request failed"); setEmail(String(data.email || email)); setMessage(result.message || "Done"); if (result.next) setMode(result.next); if (mode === "login") location.reload(); }
  const title = mode === "signup" ? "Create your workspace" : mode === "forgot" ? "Reset your password" : mode === "verify" ? "Verify your email" : mode === "reset" ? "Choose a new password" : "Welcome back";
  return <main className="min-h-screen grid place-items-center p-6"><section className="premium-login w-full max-w-md rounded-2xl p-8"><div className="mb-7 flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-lg border border-emerald-400/30 bg-emerald-400/10 font-mono text-sm text-emerald-400">X0</div><div><p className="font-mono text-[10px] uppercase tracking-[.2em] text-emerald-400">X0DEC04T</p><p className="text-xs text-[var(--color-muted)]">Secure source protection</p></div></div><h1 className="text-2xl font-semibold tracking-tight">{title}</h1><p className="mt-2 text-sm text-[var(--color-muted)]">Access your encrypted workspace.</p>{error && <p className="mt-4 rounded-lg bg-red-400/10 p-3 text-xs text-red-300">{error}</p>}{message && <p className="mt-4 rounded-lg bg-emerald-400/10 p-3 text-xs text-emerald-300">{message}</p>}<form onSubmit={submit} className="mt-6 space-y-3">{mode === "signup" && <input name="name" required placeholder="Full name" className="auth-input" />}{mode !== "verify" && <input name="email" type="email" required value={email} onChange={e => setEmail(e.target.value)} placeholder="you@example.com" className="auth-input" />}{(mode === "login" || mode === "signup" || mode === "reset") && <input name="password" type="password" required placeholder="Password" className="auth-input" />}{(mode === "verify" || mode === "reset") && <input name="code" required inputMode="numeric" pattern="[0-9]{6}" placeholder="6-digit code" className="auth-input text-center font-mono tracking-[.4em]" />}<button className="w-full rounded-lg bg-emerald-400 px-4 py-3 text-sm font-semibold text-zinc-950 transition hover:bg-emerald-300">{mode === "forgot" ? "Send reset code" : mode === "verify" ? "Verify email" : mode === "reset" ? "Reset password" : mode === "signup" ? "Create account" : "Sign in"}</button></form><div className="mt-5 flex justify-between text-xs text-[var(--color-muted)]"><button onClick={() => setMode(mode === "login" ? "signup" : "login")} className="hover:text-emerald-400">{mode === "login" ? "Create an account" : "Back to sign in"}</button>{mode === "login" && <button onClick={() => setMode("forgot")} className="hover:text-emerald-400">Forgot password?</button>}</div></section></main>;
}
